# Generated by Django 5.1.4 on 2025-01-07 20:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
