# Generated by Django 5.1.4 on 2025-01-09 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="color",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="dimensiones",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producto",
            name="marca",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
