# Generated by Django 5.1.4 on 2025-01-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_producto_activo_producto_codigo_barras_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="activo",
        ),
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.BooleanField(
                choices=[(True, "Activo"), (False, "Inactivo")], default=True
            ),
        ),
    ]
