# Generated by Django 5.1.4 on 2025-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_remove_producto_activo_producto_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="color",
            field=models.CharField(
                choices=[
                    ("BL", "Blanco"),
                    ("NG", "Negro"),
                    ("RJ", "Rojo"),
                    ("AZ", "Azul"),
                    ("VR", "Verde"),
                    ("AM", "Amarillo"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
