# Generated by Django 5.1.4 on 2025-01-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_producto_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"ordering": ["-fecha_actualizacion", "-fecha_creacion"]},
        ),
        migrations.AddField(
            model_name="producto",
            name="estado_publicacion",
            field=models.CharField(
                choices=[
                    ("PUB", "Publicado"),
                    ("BOR", "Borrador"),
                    ("PRI", "Privado"),
                ],
                default="BOR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_publicacion",
            field=models.DateTimeField(null=True),
        ),
    ]
