# Generated by Django 5.1.4 on 2025-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0005_alter_producto_options_producto_estado_publicacion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
